AllCops:
  Exclude:
    - 'Gemfile'
    - 'spec/spec_helper.rb'
    - '12_magic_seven_spec.rb'
  NewCops: enable
Metrics/BlockLength:
  Exclude:
    - 'spec/*'
    - 'spec_answers/*'
Layout/LineLength:
  Exclude:
    - 'spec/*'
    - 'spec_answers/*'
  